---

caddy_email: ihor@kalnytskyi.com

vaultwarden_domain: vault.kalnytskyi.com
vaultwarden_data: /mnt/data/vaultwarden
vaultwarden_env_settings:
  DOMAIN: https://{{ vaultwarden_domain }}
  INVITATION_ORG_NAME: The Vault
  SIGNUPS_ALLOWED: false
  SIGNUPS_VERIFY: true
  WEBSOCKET_ENABLED: true
  SMTP_USERNAME: vault@m.kalnytskyi.com
  SMTP_PASSWORD: "{{ vaultwarden_smtp_password }}"
  SMTP_HOST: smtp.eu.mailgun.org
  SMTP_FROM: vault@kalnytskyi.com
  SMTP_FROM_NAME: The Vault
  SMTP_PORT: 587
  YUBICO_CLIENT_ID: "{{ vaultwarden_yubico_client_id }}"
  YUBICO_SECRET_KEY: "{{ vaultwarden_yubico_secret_key }}"
  ROCKET_CLI_COLORS: false
  ROCKET_WORKERS: 5

wireguard_peers:
  - public_key: NK6M8U3ET3QZv2VKBO2pi14FYDuttlTLikMu6Zr8kkY=
    ip_address: 10.0.0.5
    comment: yavin
  - public_key: BGGnQMtWct0TQlCa+tT8X/fBOH7wHXG2ExEZcRoDvBE=
    ip_address: 10.0.0.10
    comment: endor
  - public_key: 4hSpNmn9YVgyu7znj9E2MoyAjGmhU6htCcP1gI3OSTs=
    ip_address: 10.0.0.11
    comment: hoth
  - public_key: 83smacMy8s1wW5SRztjy/dokD+avAjNQpZBjN7e8kXc=
    ip_address: 10.0.0.12
    comment: bespin
  - public_key: p+ea9a02hrqaRo+lCVO6XerTudT7iBDnCBwKAI+yA3E=
    ip_address: 10.0.0.20
    comment: lotrienlaptop
  - public_key: 5+FbI/E9F3CJd4UT9LeMC3vjesH2PsVQ72k9kEwsdzg=
    ip_address: 10.0.0.21
    comment: lotrienphone
