---

_storage_device_mountpoint: /mnt/data

caddy_email: ihor@kalnytskyi.com

kopia_snapshots:
  - target: "{{ _storage_device_mountpoint }}"

storage_device: /dev/disk/by-id/scsi-0HC_Volume_101710174
storage_mountpoints:
  # The block storage device to store the most important data on. Since VMs
  # root disks are ephemeral in many cloud providers, using block storage
  # device to persist your data is a good idea.
  - what: "{{ storage_device }}"
    where: "{{ _storage_device_mountpoint }}"
    type: ext4
    options: defaults
    directory_mode: "0700"

  # Vaultwarden is running with sandboxing configured with no access to block
  # storage device and without any knowledge about it. Let's just make sure
  # that the directory Vaultwarden stores its state is mounted from the block
  # storage.
  - what: /mnt/data/vaultwarden
    where: /var/lib/private/vaultwarden
    options: bind

vaultwarden_domain: vault.kalnytskyi.com
vaultwarden_env_settings:
  DOMAIN: https://{{ vaultwarden_domain }}
  INVITATION_ORG_NAME: The Vault
  SIGNUPS_ALLOWED: false
  SIGNUPS_VERIFY: true
  SMTP_USERNAME: vault@m.kalnytskyi.com
  SMTP_PASSWORD: "{{ vaultwarden_smtp_password }}"
  SMTP_HOST: smtp.eu.mailgun.org
  SMTP_FROM: vault@kalnytskyi.com
  SMTP_FROM_NAME: The Vault
  SMTP_PORT: 587
  YUBICO_CLIENT_ID: "{{ vaultwarden_yubico_client_id }}"
  YUBICO_SECRET_KEY: "{{ vaultwarden_yubico_secret_key }}"
  PUSH_ENABLED: true
  PUSH_INSTALLATION_ID: "{{ vaultwarden_push_installation_id }}"
  PUSH_INSTALLATION_KEY: "{{ vaultwarden_push_installation_key }}"
  PUSH_RELAY_URI: https://api.bitwarden.eu
  PUSH_IDENTITY_URI: https://identity.bitwarden.eu
  ROCKET_CLI_COLORS: false
  ROCKET_WORKERS: 5

wireguard_peers:
  - public_key: NK6M8U3ET3QZv2VKBO2pi14FYDuttlTLikMu6Zr8kkY=
    ip_address: 192.168.4.5
    comment: yavin
  - public_key: BGGnQMtWct0TQlCa+tT8X/fBOH7wHXG2ExEZcRoDvBE=
    ip_address: 192.168.4.10
    comment: endor
  - public_key: 4hSpNmn9YVgyu7znj9E2MoyAjGmhU6htCcP1gI3OSTs=
    ip_address: 192.168.4.11
    comment: hoth
  - public_key: 83smacMy8s1wW5SRztjy/dokD+avAjNQpZBjN7e8kXc=
    ip_address: 192.168.4.12
    comment: bespin
  - public_key: /dwRWPbLDRs8rT2alMvH7BXqDFrzDRGAxakT3KnSJ2U=
    ip_address: 192.168.4.13
    comment: alderaan
  - public_key: p+ea9a02hrqaRo+lCVO6XerTudT7iBDnCBwKAI+yA3E=
    ip_address: 192.168.4.20
    comment: lotrienlaptop
  - public_key: 5+FbI/E9F3CJd4UT9LeMC3vjesH2PsVQ72k9kEwsdzg=
    ip_address: 192.168.4.21
    comment: lotrienphone
  - public_key: HB/55xINQU4SyPZvWH9mKybs7+7uPc6wZM4I7aLnSm4=
    ip_address: 192.168.4.22
    comment: lotrientablet
  - public_key: wqMjN1Jvc4mSUeI5G9YdgK+Q724DWlKDsznE8tYbIB8=
    ip_address: 192.168.4.33
    comment: propheticbird
