---

- name: Provision
  hosts: hoth
  roles:
    - role: hardening
    - role: storage
    - role: kopia
    - role: jumphost
    - role: wireguard
    - role: vaultwarden
    - role: caddy
    - role: caddy_confd
