---

- name: Render Caddy configuration for Vaultwarden
  ansible.builtin.template:
    src: vaultwarden.caddy.j2
    dest: "{{ (caddy_confd_path, 'vaultwarden.caddy') | path_join }}"
    mode: u=rw,g=r,o=r
  notify: caddy-restart
  become: true
