---

- name: Add caddy deb repo
  ansible.builtin.deb822_repository: "{{ caddy_deb_repo }}"
  register: caddy_deb_repo_result
  become: true

- name: Update apt cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: caddy_deb_repo_result.changed
  become: true

- name: Install apt prerequisite packages
  ansible.builtin.apt:
    name: "{{ caddy_prerequisite_packages }}"
    state: present
  become: true

- name: Install caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  become: true

- name: Configure caddy to serve virtual hosts from multiple files
  ansible.builtin.template:
    src: caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: u=rw,g=r,o=r
  become: true

- name: Create conf.d directory to store virtual hosts
  ansible.builtin.file:
    path: "{{ caddy_confd_path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Start caddy now and on every reboot
  ansible.builtin.systemd:
    name: caddy.service
    enabled: true
    state: restarted
  become: true
