---

dependencies:
  - role: podman

argument_specs:
  main:
    options:
      vaultwarden_domain:
        type: str
        required: true
        description: |
          The domain to serve requests from.
      vaultwarden_data:
        type: str
        required: true
        description: |
          An absolute path to the directory to store vaultwarden state in.
      vaultwarden_user:
        type: str
        default: vault
        description: |
          The user to run vaultwarden under. If the user does not exist, it
          will be created.
      vaultwarden_host:
        type: str
        default: 127.0.0.1
        description: |
          The host address to bind vaultwarden to.
      vaultwarden_port:
        type: int
        default: 5000
        description: |
          The port to bind vaultwarden to.
