---

argument_specs:
  main:
    options:
      vaultwarden_domain:
        type: str
        required: true
        description: |
          The domain to serve requests from.
      vaultwarden_host:
        type: str
        default: 127.0.0.1
        description: |
          The host address to bind Vaultwarden to.
      vaultwarden_port:
        type: int
        default: 5000
        description: |
          The port to bind Vaultwarden to.
      vaultwarden_ws_port:
        type: int
        default: 5001
        description: |
          The websocket port to bind Vaultwarden to.
      vaultwarden_env_settings:
        type: dict
        default: {}
        description: |
          The Vaultwarden settings passed "As Is" to the service. See
          Vaultwarden's `.env.template` for supported options.
