---

ntfy_deb_repo_name: ntfy
ntfy_deb_repo_types: deb
ntfy_deb_repo_uris: https://archive.ntfy.sh/apt
ntfy_deb_repo_suites: stable
ntfy_deb_repo_components: main
ntfy_deb_repo_signed_by: https://archive.ntfy.sh/apt/keyring.gpg
