---

- name: Create Vaultwarden secret
  ansible.builtin.command:
    cmd: systemd-creds encrypt - /etc/credstore.encrypted/{{ item.key }}
    stdin: "{{ item.value }}"
  loop: "{{ vaultwarden_secrets | dict2items }}"
  changed_when: true
  become: true

- name: Fetch and unpack Vaultwarden image
  oci_image_unpack:
    image: "{{ vaultwarden_image }}"
    destination: "{{ vaultwarden_root }}"
  become: true

- name: Create data and settings directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: u=rw,g=,o=
    state: directory
  with_items:
    - "{{ vaultwarden_etc }}"
  become: true

- name: Generate vaultwarden systemd service unit
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/vaultwarden.service
    mode: u=rw,g=r,o=r
  become: true

- name: Start vaultwarden now and on every reboot
  ansible.builtin.systemd:
    name: vaultwarden.service
    enabled: true
    state: restarted
    daemon_reload: true
  become: true
