---

- name: generate systemd mount unit name
  ansible.builtin.command: systemd-escape -p --suffix=mount {{ item.where }}
  register: systemd_escape
  changed_when: false

- name: set systemd mount unit name
  ansible.builtin.set_fact:
    unit_name: "{{ systemd_escape.stdout }}"

- name: render systemd mount unit
  ansible.builtin.template:
    src: systemd.mount.j2
    dest: /usr/lib/systemd/system/{{ unit_name }}
    mode: u=rw,g=r,o=r
  become: true

- name: start systemd mount unit and on every reboot
  ansible.builtin.systemd:
    name: "{{ unit_name }}"
    enabled: true
    state: started
    daemon_reload: true
  become: true
