---

caddy_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
caddy_deb_repo:
  name: caddy
  types: deb
  uris: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
  suites: any-version
  components: main
  signed_by: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
