name: CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: hoth.kalnytskyi.com
    concurrency: hoth.kalnytskyi.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade ansible

      - name: Install playbook dependencies
        run: |
          sudo apt install skopeo umoci rsync

      - name: Setup a deployment SSH key
        run: |
          DEPLOY_SSH_PRIVATE_KEY='${{ runner.temp }}/id_ed25519'
          echo '${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}' > $DEPLOY_SSH_PRIVATE_KEY
          chmod 0600 $DEPLOY_SSH_PRIVATE_KEY
          echo "uri=$DEPLOY_SSH_PRIVATE_KEY" >> $GITHUB_OUTPUT
        id: ssh-key

      - name: Deploy to production
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}' >> ~/.ssh/known_hosts

          ansible-galaxy collection install -r requirements.yml

          ansible-playbook \
            -vv \
            --inventory inventory \
            --private-key '${{ steps.ssh-key.outputs.uri }}' \
            --extra-vars vaultwarden_smtp_password='${{ secrets.VAULTWARDEN_SMTP_PASSWORD }}' \
            --extra-vars vaultwarden_yubico_client_id='${{ secrets.VAULTWARDEN_YUBICO_CLIENT_ID }}' \
            --extra-vars vaultwarden_yubico_secret_key='${{ secrets.VAULTWARDEN_YUBICO_SECRET_KEY }}' \
            --extra-vars wireguard_private_key='${{ secrets.WIREGUARD_PRIVATE_KEY }}' \
            site.yml
